-- Schema and migration for the hackathon API on Supabase.
-- Run in Supabase SQL Editor with the postgres role.

create extension if not exists pgcrypto;

-- Existing domain tables used by the C++ backend.
create table if not exists universidades (
    iduniversidad bigint generated by default as identity primary key,
    nombre_uni varchar(160) not null
);

create table if not exists problematica (
    idproblematica bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    descripcion text not null default '',
    codigo varchar(20)
);

create table if not exists contactoemergencia (
    idcontacto bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    telefono varchar(40) not null,
    pariente varchar(80) not null
);

create table if not exists equipo (
    idequipo bigint generated by default as identity primary key,
    nombre_equipo varchar(160) not null,
    iduniversidad bigint,
    idlider bigint,
    idproblematica bigint not null,
    estado varchar(20) not null default 'pendiente',
    registrado_en timestamptz not null default now(),
    revisado_en timestamptz,
    notas text,
    constraint equipo_estado_ck check (estado in ('pendiente', 'aceptado', 'rechazado'))
);

create table if not exists alumnos (
    idalumno bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    idequipo bigint not null,
    firmoterminos boolean not null default false,
    correo varchar(320) not null,
    numerotel varchar(40) not null default '',
    apellidopaterno varchar(100) not null default '',
    apellidomaterno varchar(100) not null default '',
    alergias text not null default '',
    condicion varchar(255) not null default '',
    medicamento varchar(255) not null default '',
    idcontacto bigint,
    iduniversidad bigint,
    institucion varchar(200) not null default ''
);

create table if not exists registro (
    idregistro bigint generated by default as identity primary key,
    fecha_hora_registro timestamptz not null default now(),
    idequipo bigint not null
);

create table if not exists admin (
    adminid bigint generated by default as identity primary key,
    nombre varchar(160) not null,
    correo_aes text not null,
    contrasena text not null,
    correo_hmac text not null
);

-- Make the migration compatible with installations created from the old diagram.
alter table universidades add column if not exists nombre_uni varchar(160) not null default '';
alter table problematica add column if not exists codigo varchar(20);
alter table problematica add column if not exists nombre varchar(160) not null default '';
alter table problematica add column if not exists descripcion text not null default '';
alter table equipo add column if not exists iduniversidad bigint;
alter table equipo add column if not exists nombre_equipo varchar(160) not null default '';
alter table equipo add column if not exists idlider bigint;
alter table equipo add column if not exists idproblematica bigint;
alter table alumnos add column if not exists institucion varchar(200) not null default '';
alter table alumnos add column if not exists nombre varchar(160) not null default '';
alter table alumnos add column if not exists idequipo bigint;
alter table alumnos add column if not exists firmoterminos boolean not null default false;
alter table alumnos add column if not exists correo varchar(320) not null default '';
alter table alumnos add column if not exists numerotel varchar(40) not null default '';
alter table alumnos add column if not exists apellidopaterno varchar(100) not null default '';
alter table alumnos add column if not exists apellidomaterno varchar(100) not null default '';
alter table alumnos add column if not exists alergias text not null default '';
alter table alumnos add column if not exists condicion varchar(255) not null default '';
alter table alumnos add column if not exists medicamento varchar(255) not null default '';
alter table alumnos add column if not exists idcontacto bigint;
alter table alumnos add column if not exists iduniversidad bigint;
alter table equipo add column if not exists estado varchar(20) not null default 'pendiente';
alter table equipo add column if not exists registrado_en timestamptz not null default now();
alter table equipo add column if not exists revisado_en timestamptz;
alter table equipo add column if not exists notas text;
alter table contactoemergencia add column if not exists nombre varchar(160) not null default '';
alter table contactoemergencia add column if not exists telefono varchar(40) not null default '';
alter table contactoemergencia add column if not exists pariente varchar(80) not null default '';
alter table registro add column if not exists fecha_hora_registro timestamptz not null default now();
alter table registro add column if not exists idequipo bigint;
alter table admin add column if not exists nombre varchar(160) not null default '';
alter table admin add column if not exists correo_aes text not null default '';
alter table admin add column if not exists contrasena text not null default '';
alter table admin add column if not exists correo_hmac text not null default '';

create index if not exists problematica_codigo_idx on problematica (codigo);
create unique index if not exists problematica_codigo_uidx
    on problematica (codigo) where codigo is not null;
create index if not exists alumnos_idequipo_idx on alumnos (idequipo);
create index if not exists alumnos_correo_idx on alumnos (correo);
create index if not exists equipo_estado_idx on equipo (estado);
create index if not exists registro_idequipo_idx on registro (idequipo);
create unique index if not exists admin_correo_hmac_uidx on admin (correo_hmac);

-- The current C++ models use -1 for an optional foreign key. Normalize that
-- sentinel before foreign-key validation so registration can omit university.
create or replace function normalizar_ids_opcionales()
returns trigger
language plpgsql
as $$
begin
    if tg_table_name = 'equipo' and new.iduniversidad = -1 then
        new.iduniversidad := null;
    elsif tg_table_name = 'alumnos' then
        if new.idcontacto = -1 then new.idcontacto := null; end if;
        if new.iduniversidad = -1 then new.iduniversidad := null; end if;
    end if;
    return new;
end;
$$;

drop trigger if exists equipo_normalizar_ids on equipo;
create trigger equipo_normalizar_ids
before insert or update on equipo
for each row execute function normalizar_ids_opcionales();

drop trigger if exists alumno_normalizar_ids on alumnos;
create trigger alumno_normalizar_ids
before insert or update on alumnos
for each row execute function normalizar_ids_opcionales();

-- Foreign keys are added only when absent. The equipo/alumnos leader relation is
-- intentionally omitted because it is circular during registration.
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'equipo_universidad_fk') then
        alter table equipo add constraint equipo_universidad_fk
            foreign key (iduniversidad) references universidades (iduniversidad);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'equipo_problematica_fk') then
        alter table equipo add constraint equipo_problematica_fk
            foreign key (idproblematica) references problematica (idproblematica);
    end if;
    if not exists (select 1 from pg_constraint where conname = 'alumno_equipo_fk') then
        alter table alumnos add constraint alumno_equipo_fk
            foreign key (idequipo) references equipo (idequipo) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'alumno_contacto_fk') then
        alter table alumnos add constraint alumno_contacto_fk
            foreign key (idcontacto) references contactoemergencia (idcontacto) on delete set null;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'alumno_universidad_fk') then
        alter table alumnos add constraint alumno_universidad_fk
            foreign key (iduniversidad) references universidades (iduniversidad) on delete set null;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'registro_equipo_fk') then
        alter table registro add constraint registro_equipo_fk
            foreign key (idequipo) references equipo (idequipo) on delete cascade;
    end if;
end $$;

-- Event configuration. There is one active configuration row.
create table if not exists evento_configuracion (
    id smallint primary key default 1 check (id = 1),
    cupo integer not null default 60 check (cupo > 0),
    min_integrantes smallint not null default 3 check (min_integrantes > 0),
    max_integrantes smallint not null default 5 check (max_integrantes >= min_integrantes),
    registro_abierto boolean not null default true,
    updated_at timestamptz not null default now()
);

insert into evento_configuracion (id)
values (1)
on conflict (id) do nothing;

-- Agenda and staff use text IDs because those are the IDs in the frontend contract.
create table if not exists staff (
    id text primary key default ('staff-' || gen_random_uuid()::text),
    nombre varchar(160) not null,
    rol varchar(100) not null,
    area varchar(100) not null default '',
    correo varchar(320) not null,
    telefono varchar(40) not null default '',
    created_at timestamptz not null default now()
);

create table if not exists agenda (
    id text primary key default ('ev-' || gen_random_uuid()::text),
    dia varchar(20) not null,
    inicio time not null,
    fin time not null,
    titulo varchar(200) not null,
    detalle text,
    tipo varchar(40) not null default 'service',
    created_at timestamptz not null default now(),
    constraint agenda_horario_ck check (fin > inicio)
);

create table if not exists agenda_responsable (
    agenda_id text not null references agenda(id) on delete cascade,
    staff_id text not null references staff(id) on delete cascade,
    primary key (agenda_id, staff_id)
);

create index if not exists agenda_dia_inicio_idx on agenda (dia, inicio);

create table if not exists patrocinadores (
    id text primary key default ('sp-' || gen_random_uuid()::text),
    nombre varchar(180) not null,
    logo text not null default '',
    url text not null default '',
    nivel varchar(30) not null default 'aliado',
    created_at timestamptz not null default now(),
    constraint patrocinadores_nivel_ck check (nivel in ('principal', 'aliado'))
);

create table if not exists correo_configuracion (
    id smallint primary key default 1 check (id = 1),
    configurado boolean not null default false,
    habilitado boolean not null default false,
    remitente varchar(320) not null default '',
    updated_at timestamptz not null default now()
);

-- Complete partially-created contract tables as well.
alter table evento_configuracion add column if not exists cupo integer not null default 60;
alter table evento_configuracion add column if not exists min_integrantes smallint not null default 3;
alter table evento_configuracion add column if not exists max_integrantes smallint not null default 5;
alter table evento_configuracion add column if not exists registro_abierto boolean not null default true;
alter table evento_configuracion add column if not exists updated_at timestamptz not null default now();
alter table staff add column if not exists nombre varchar(160) not null default '';
alter table staff add column if not exists rol varchar(100) not null default '';
alter table staff add column if not exists area varchar(100) not null default '';
alter table staff add column if not exists correo varchar(320) not null default '';
alter table staff add column if not exists telefono varchar(40) not null default '';
alter table staff add column if not exists created_at timestamptz not null default now();
alter table agenda add column if not exists dia varchar(20) not null default '';
alter table agenda add column if not exists inicio time not null default '00:00';
alter table agenda add column if not exists fin time not null default '00:01';
alter table agenda add column if not exists titulo varchar(200) not null default '';
alter table agenda add column if not exists detalle text;
alter table agenda add column if not exists tipo varchar(40) not null default 'service';
alter table agenda add column if not exists created_at timestamptz not null default now();
alter table patrocinadores add column if not exists nombre varchar(180) not null default '';
alter table patrocinadores add column if not exists logo text not null default '';
alter table patrocinadores add column if not exists url text not null default '';
alter table patrocinadores add column if not exists nivel varchar(30) not null default 'aliado';
alter table patrocinadores add column if not exists created_at timestamptz not null default now();
alter table correo_configuracion add column if not exists configurado boolean not null default false;
alter table correo_configuracion add column if not exists habilitado boolean not null default false;
alter table correo_configuracion add column if not exists remitente varchar(320) not null default '';
alter table correo_configuracion add column if not exists updated_at timestamptz not null default now();

insert into correo_configuracion (id)
values (1)
on conflict (id) do nothing;

-- Helpful seed data. It is safe to run repeatedly.
insert into problematica (codigo, nombre, descripcion)
values ('01', 'Salud', '')
on conflict do nothing;

-- Supabase security: this backend connects with DATABASE_URL and performs
-- authorization in AuthMiddleware. Keep these tables private to anon/auth roles.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
